[package]
name = "quick"
version = "0.1.0"
edition = "2021"
author = "Ahmed Ibrahim"

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
colored = "2.0.0"
regex = "1.6.0"
thiserror = "1.0.34"
